### ISSUE TITLE
Empty Event.log

### ISSUE THREAD

**Issue by irisshannon** [codefresh-support/codefresh-support-package#11]
Recently used the support package, but the event.logs came back blank, but everything else came back fine.  Did you think this might be a bug, or a event resource allocation issue/user error?  I can't seem to repo it.

**Comment by lukasmagik** [comment]
Are you looking at the events.txt file? It could be that there were no new events in the Namespace. When I ran the support package and the equivalent kubectl command, I confirmed that there were no events.
